<!-- Generated by IcoMoon.io -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
<title>takeout_dining</title>
<path d="M9 3.984h5.953l4.031 3.375 1.594-1.547 1.406 1.406-2.766 2.766h-14.438l-2.766-2.766 1.406-1.406 1.594 1.547zM5.25 11.016h13.5l-0.703 9h-12.094z"></path>
</svg>
